cmake_minimum_required(VERSION 3.31)
project(compe1)

set(CMAKE_CXX_STANDARD 20)

add_executable(compe1 2250B-string-construction.cpp)
add_executable(2248b 2248b-merge-to-match.cpp)
add_executable(2247c 2247c-inversion-of-a-subsequence.cpp)
add_executable(2245b 2245b-delete-and-concatenate.cpp)
add_executable(2244d 2244d-yaroslav-and-productivity.cpp
        264a.cpp)
add_executable(lab1a lab1a-lever.cpp)
add_executable(lab1b lab1b-alternating-series.cpp)
add_executable(lab1c lab1c-make-it-equal.cpp)
add_executable(lab1d lab1d-only-one-digit.cpp)
add_executable(lab1e lab1e-no-casino-in-the-mountains.cpp)
add_executable(lab1f lab1f-i-will-definitely-make-it.cpp)
add_executable(eda1 eda1.cpp)
add_executable(eda2 eda2.cpp)
add_executable(c1a c1a.cpp)
add_executable(c1b c1b.cpp)
add_executable(c1c c1c.cpp)
add_executable(c1d c1d.cpp)
add_executable(c1e c1e.cpp)
add_executable(2254c2 2254c2.cpp)
add_executable(2253b 2253b.cpp)
add_executable(eda3 eda3.cpp)
add_executable(eda4 eda4.cpp)
add_executable(eda2_backup eda2_backup.cpp)
add_executable(TEST cmake-build-debug/TEST.cpp)
add_executable(2254d 2254d.cpp)
add_executable(book-s2-1d-10978 book-s2-1d-10978.cpp)
add_executable(book-s2-1d-11222 book-s2-1d-11222.cpp)
add_executable(book-s2-1d-13048 book-s2-1d-13048.cpp)
add_executable(book-s2-sorting-10258 book-s2-sorting-10258.cpp)
add_executable(264a 264a.cpp)
add_executable(262b 262b.cpp)
add_executable(259b 259b.cpp)
add_executable(259a 259a.cpp)
add_executable(lab2a lab2a.cpp)
add_executable(lab2b lab2b.cpp)
add_executable(lab2c lab2c.cpp)
add_executable(lab2d lab2d.cpp)
add_executable(c2a c2a.cpp)
add_executable(c2b c2b.cpp c2b.h)
add_executable(c2breal c2breal.cpp)
add_executable(c2c c2c.cpp)
add_executable(c2d c2d.cpp)
add_executable(c2e c2e.cpp)
add_executable(backtracking-function backtracking-function.cpp)
add_executable(backtracking-function-2 backtracking-function-2.cpp)
add_executable(eda-persistence-stack eda-persistence-stack.cpp)
add_executable(eda-s3-1 eda-s3-1.cpp)
add_executable(eda-s3-2 eda-s3-2.cpp)
add_executable(eda-persistence-segment-tree eda-persistence-segment-tree.cpp)
add_executable(476b 476b.cpp)
add_executable(fibonacciheapcarlos fibonacciheapcarlos.cpp)
add_executable(cpbook-5-backtrack cpbook-5-backtrack.cpp)
add_executable(s3-nqueens-profe s3-nqueens-profe.cpp)
add_executable(c3a c3a.cpp)
add_executable(c3b c3b.cpp)
add_executable(c3c c3c.cpp)
add_executable(c3d c3d.cpp)
add_executable(c3e c3e.cpp)
add_executable(c3f c3f.cpp)
add_executable(c3g c3g.cpp)
add_executable(c3h c3h.cpp)
add_executable(cpc2a cpc2a.cpp)
add_executable(cpc2c cpc2c.cpp)
add_executable(contest1118a contest1118a.cpp)
add_executable(s3b s3b.cpp)
add_executable(gcf_test gcf_test.cpp)
add_executable(contest1118c contest1118c.cpp)
add_executable(contest1118b contest1118b.cpp)
add_executable(c2f c2f.cpp)
add_executable(c3d-again c3d-again.cpp)
add_executable(contest1003a contest1003a.cpp)
add_executable(contest1003b contest1003b.cpp)
add_executable(contest1003d contest1003d.cpp)
add_executable(contest1003e contest1003e.cpp)
add_executable(contest1006a 1490d.cpp)
add_executable(1741d 1741d.cpp
        s5c.cpp
        contest1122d.cpp)
add_executable(1915f 1915f-readwrong.cpp)
add_executable(1915f2 1915f.cpp)
add_executable(eda-segmenttree eda-segmenttree.cpp)
add_executable(s4a s4a.cpp)
add_executable(s4b s4b.cpp)
add_executable(eda-range-tree-1d eda-range-tree-1d.cpp)
add_executable(cpc4a cpc4a.cpp)
add_executable(s4c s4c.cpp)
add_executable(c4b c4b.cpp)
add_executable(contest1119a contest1119a.cpp)
add_executable(contest1119b contest1119b.cpp)
add_executable(c4c c4c.cpp)
add_executable(c4d c4d.cpp)
add_executable(c4e c4e.cpp)
add_executable(c4e-dyc c4e-dyc.cpp)
add_executable(c4e2 c4e2.cpp)
add_executable(c4f c4f.cpp)
add_executable(edapractice-persistentstack edapractice-persistentstack.cpp)
add_executable(edapractice-stackqueue edapractice-stackqueue.cpp)
add_executable(edapractice-avl edapractice-avl.cpp)
add_executable(edapractice-segmenttree edapractice-segmenttree.cpp)
add_executable(s5a s5a.cpp)
add_executable(s5b s5b.cpp)
add_executable(s5c s5c.cpp)
add_executable(s5f s5f.cpp)
add_executable(contest1121a contest1121a.cpp)
add_executable(contest1121b contest1121b.cpp)
add_executable(contest1121c contest1121c.cpp)
add_executable(eda-persistentqueue eda-persistentqueue.cpp)
add_executable(s6b s6b.cpp)
add_executable(eda-simulacro-a eda-simulacro-a.cpp)
add_executable(s6a s6a.cpp)
add_executable(s6b2 s6b2.cpp)
add_executable(s6c s6c.cpp)
add_executable(s6f s6f.cpp)
add_executable(c6b c6b.cpp)
add_executable(c6otra c6otra.cpp)
add_executable(c6d c6d.cpp)
add_executable(eda-persstpractice eda-persstpractice.cpp)
add_executable(contest1122a contest1122a.cpp)
add_executable(contest1122b contest1122b.cpp)
add_executable(contest1122c contest1122c.cpp)
add_executable(contest1122d contest1122d.cpp)
add_executable(generateprimes generateprimes.cpp)
add_executable(eda-kquery eda-kquery.cpp)
add_executable(gpc-1-1 gpc-1-1.cpp)
add_executable(eda-bbst-test eda-bbst-test.cpp)
add_executable(gpc-1-3 gpc-1-3.cpp)
add_executable(eda-persistence-1c eda-persistence-1c.cpp)
add_executable(eda-persistence-1d eda-persistence-1d.cpp)
add_executable(eda-persistence-1g eda-persistence-1g.cpp)
add_executable(cpc6a cpc6a.cpp)
add_executable(cpc6e cpc6e.cpp)
add_executable(c7a-2 c7a-2.cpp)
add_executable(c6g c6g.cpp)
add_executable(cses-money-sums cses-money-sums.cpp)
add_executable(c5b c5b.cpp)
add_executable(c5c c5c.cpp)
add_executable(eda-persistence-1h eda-persistence-1h.cpp)
add_executable(eda-persistence-1i eda-persistence-1i.cpp)
add_executable(eda-persistence-1e eda-persistence-1e.cpp)
add_executable(eda-persistence-1f eda-persistence-1f.cpp)
add_executable(eda-persistent-trie-mridul1809 eda-persistent-trie-mridul1809.cpp)
add_executable(eda-persistence-2b eda-persistence-2b.cpp)
add_executable(eda-persistence-2c eda-persistence-2c.cpp)
add_executable(eda-persistence-2d eda-persistence-2d.cpp)
add_executable(eda-persistence-2e eda-persistence-2e.cpp)
add_executable(eda-simulacro-a-racso eda-simulacro-a-racso.cpp)
add_executable(eda-simulacro-b-racso eda-simulacro-b-racso.cpp)
add_executable(eda-persistence-1k eda-persistence-1k.cpp)
add_executable(eda-arithmetic-exercise eda-trie-with-mex-untested.cpp)
add_executable(eda-940f-machine-learning eda-940f-machine-learning.cpp)
